# Generated by Django 4.0.2 on 2023-02-20 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='марка')),
                ('model', models.CharField(max_length=50, verbose_name='модель')),
                ('year', models.CharField(max_length=4, verbose_name='год')),
                ('mark', models.CharField(choices=[(None, 'Без оценки'), ('good', 'Хорошее'), ('medium', 'Среднее'), ('bad', 'Ниже среднего')], default=None, max_length=15, verbose_name='оценка состояния')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('term', models.CharField(choices=[('1', '1 месяц'), ('2', '3 месяца'), ('3', '6 месяцев')], default='1', max_length=15, verbose_name='срок сдачи')),
                ('status', models.CharField(choices=[('not_available', 'Сдана'), ('available', 'Сдается'), ('booking', 'Забронирована')], default='available', max_length=15, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(default=None, max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(default=None, max_length=100, verbose_name='Отчество')),
                ('passport', models.IntegerField(verbose_name='Серия и номер ВУ')),
                ('_type', models.CharField(choices=[('online', 'Онлайн'), ('arend', 'Сдает'), ('buyer', 'Арендует')], default='online', max_length=15, verbose_name='тип')),
            ],
        ),
        migrations.CreateModel(
            name='UserCli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=10, verbose_name='Никнейм')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('passport', models.IntegerField(verbose_name='Серия и номер ВУ')),
                ('_type', models.CharField(choices=[('online', 'Онлайн'), ('arend', 'Сдает'), ('buyer', 'Арендует')], default='online', max_length=15, verbose_name='тип')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_car', to='main.car')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_client', to='main.client')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client', verbose_name='Хозяин'),
        ),
    ]
